-- ============================================================
-- TENNIS PREDICTOR
-- Sistema de Gestão de Quota API
-- ============================================================
-- COMO EXECUTAR:
-- 1. Ir ao Supabase Dashboard: https://supabase.com/dashboard
-- 2. Selecionar o projeto
-- 3. Ir a SQL Editor
-- 4. Colar este SQL e executar
-- ============================================================


-- ============================================================
-- 1. API CONFIG
-- Parâmetros configuráveis do sistema de quota
-- ============================================================

create table if not exists public.api_config (
    key text primary key,
    value text not null,
    description text,
    updated_at timestamptz not null default now()
);

-- Inserir configuração padrão
insert into public.api_config (key, value, description) values
    ('daily_limit', '90', 'Limite operacional de requests por dia (absoluto: 100)'),
    ('requests_per_hour_during_games', '6', 'Máximo de requests/hora durante período de jogos'),
    ('morning_sync_hour', '8', 'Hora do sync matinal (0-23)'),
    ('pre_game_window_hours', '2', 'Horas antes do primeiro jogo para preparar dados'),
    ('min_requests_reserved', '10', 'Requests reservados como margem de segurança no final do dia'),
    ('live_poll_interval_minutes', '15', 'Intervalo mínimo entre polls de resultados Live')
on conflict (key) do update set
    value = excluded.value,
    description = excluded.description,
    updated_at = now();


-- ============================================================
-- 2. SYNC SCHEDULE
-- Planeamento de quando sincronizar o quê
-- ============================================================

create table if not exists public.sync_schedule (
    id bigint generated by default as identity primary key,

    scheduled_date date not null,

    sync_type text not null check (
        sync_type in ('morning_sync', 'pre_game', 'live_poll', 'post_game')
    ),

    scheduled_at timestamptz not null,

    status text not null default 'pending' check (
        status in ('pending', 'in_progress', 'completed', 'failed', 'skipped')
    ),

    matches_expected integer,

    matches_processed integer,

    requests_consumed integer default 0,

    started_at timestamptz,

    completed_at timestamptz,

    error_message text,

    created_at timestamptz not null default now()
);

create index if not exists idx_sync_schedule_date_type
    on public.sync_schedule(scheduled_date, sync_type);

create index if not exists idx_sync_schedule_status
    on public.sync_schedule(status);


-- ============================================================
-- 3. FUNÇÃO: Requests disponíveis restantes no dia
-- ============================================================

create or replace function public.get_remaining_requests()
returns integer
language sql
as $$
    select greatest(
        (select cast(value as integer) from public.api_config where key = 'daily_limit')
        - coalesce(
            (select requests_used from public.api_usage where usage_date = current_date),
            0
        ),
        0
    );
$$;


-- ============================================================
-- 4. FUNÇÃO: Requests usados na hora atual
-- ============================================================

create or replace function public.get_hourly_usage()
returns integer
language sql
as $$
    select count(*)
    from public.api_requests
    where requested_at >= date_trunc('hour', now())
      and requested_at < date_trunc('hour', now()) + interval '1 hour';
$$;


-- ============================================================
-- 5. FUNÇÃO: Horário do primeiro e último jogo do dia
-- ============================================================

create or replace function public.get_today_game_window()
returns table (
    first_game_at timestamptz,
    last_game_at timestamptz,
    total_games integer
)
language sql
as $$
    select
        min(m.scheduled_at),
        max(m.scheduled_at),
        count(*)
    from public.matches m
    where m.scheduled_at::date = current_date
      and m.status in ('upcoming', 'live');
$$;


-- ============================================================
-- 6. FUNÇÃO MELHORADA: can_make_api_request()
-- Agora verifica quota diária + distribuição horária
-- ============================================================

create or replace function public.can_make_api_request()
returns boolean
language plpgsql
as $$
declare
    daily_limit integer;
    min_reserved integer;
    current_usage integer;
    remaining integer;
    hourly_limit integer;
    hourly_usage integer;
    first_game timestamptz;
    last_game timestamptz;
    total_games integer;
    is_during_games boolean;
begin
    -- Obter configuração
    select cast(value as integer) into daily_limit
    from public.api_config where key = 'daily_limit';

    select cast(value as integer) into min_reserved
    from public.api_config where key = 'min_requests_reserved';

    select cast(value as integer) into hourly_limit
    from public.api_config where key = 'requests_per_hour_during_games';

    -- Verificar quota diária
    current_usage := public.get_api_usage(current_date);
    remaining := daily_limit - current_usage;

    if remaining <= min_reserved then
        return false;
    end if;

    -- Verificar rate limit por hora
    hourly_usage := public.get_hourly_usage();

    -- Determinar se estamos em período de jogos
    select * into first_game, last_game, total_games
    from public.get_today_game_window();

    if total_games = 0 or total_games is null then
        -- Sem jogos hoje: limite conservador (2/hora)
        return hourly_usage < 2;
    end if;

    is_during_games := now() >= (first_game - interval '2 hours')
                      and now() <= (last_game + interval '1 hour');

    if is_during_games then
        -- Durante jogos: até requests_per_hour_during_games
        return hourly_usage < hourly_limit;
    else
        -- Fora do horário de jogos: 4 requests/hora (1 a cada 15 min)
        return hourly_usage < 4;
    end if;
end;
$$;


-- ============================================================
-- 7. FUNÇÃO: Obter próximo sync agendado
-- ============================================================

create or replace function public.get_next_sync()
returns table (
    sync_type text,
    scheduled_at timestamptz,
    matches_count integer
)
language sql
as $$
    select
        ss.sync_type,
        ss.scheduled_at,
        coalesce(ss.matches_expected, 0)
    from public.sync_schedule ss
    where ss.scheduled_date = current_date
      and ss.status = 'pending'
    order by ss.scheduled_at asc
    limit 1;
$$;


-- ============================================================
-- 8. FUNÇÃO: Criar schedule diário
-- Deve ser chamada após o morning_sync
-- ============================================================

create or replace function public.generate_daily_schedule()
returns void
language plpgsql
as $$
declare
    first_game timestamptz;
    last_game timestamptz;
    total_games integer;
    morning_hour integer;
    pre_game_window integer;
    poll_interval integer;
begin
    -- Obter config
    select cast(value as integer) into morning_hour
    from public.api_config where key = 'morning_sync_hour';

    select cast(value as integer) into pre_game_window
    from public.api_config where key = 'pre_game_window_hours';

    select cast(value as integer) into poll_interval
    from public.api_config where key = 'live_poll_interval_minutes';

    -- Obter janela de jogos de hoje
    select * into first_game, last_game, total_games
    from public.get_today_game_window();

    -- Limpar schedule anterior não executado
    delete from public.sync_schedule
    where scheduled_date = current_date
      and status = 'pending';

    -- 1. Morning sync
    insert into public.sync_schedule (scheduled_date, sync_type, scheduled_at, matches_expected)
    values (
        current_date,
        'morning_sync',
        (current_date + (morning_hour || ' hours')::interval),
        0
    );

    -- Se não há jogos hoje, não precisa de mais schedule
    if total_games = 0 or total_games is null then
        return;
    end if;

    -- 2. Pre-game (2 horas antes do primeiro jogo)
    if first_game > (current_date + (morning_hour || ' hours')::interval) + interval '3 hours' then
        insert into public.sync_schedule (scheduled_date, sync_type, scheduled_at, matches_expected)
        values (
            current_date,
            'pre_game',
            first_game - (pre_game_window || ' hours')::interval,
            total_games
        );
    end if;

    -- 3. Live polls (a cada poll_interval minutos durante os jogos)
    insert into public.sync_schedule (scheduled_date, sync_type, scheduled_at, matches_expected)
    select
        current_date,
        'live_poll',
        generate_series(
            first_game,
            last_game + interval '1 hour',
            (poll_interval || ' minutes')::interval
        ),
        total_games;

    -- 4. Post-game (30 min após último jogo)
    insert into public.sync_schedule (scheduled_date, sync_type, scheduled_at, matches_expected)
    values (
        current_date,
        'post_game',
        last_game + interval '30 minutes',
        total_games
    );
end;
$$;


-- ============================================================
-- 9. FUNÇÃO: Estatísticas do dia para monitorização
-- ============================================================

create or replace function public.get_daily_stats()
returns table (
    requests_used integer,
    requests_remaining integer,
    requests_limit integer,
    first_game timestamptz,
    last_game timestamptz,
    total_games integer,
    games_live integer,
    games_completed integer,
    games_upcoming integer,
    next_sync_type text,
    next_sync_at timestamptz
)
language sql
as $$
    select
        coalesce(au.requests_used, 0)::integer,
        public.get_remaining_requests(),
        (select cast(value as integer) from public.api_config where key = 'daily_limit'),
        gw.first_game_at,
        gw.last_game_at,
        gw.total_games::integer,
        (select count(*) from public.matches where scheduled_at::date = current_date and status = 'live')::integer,
        (select count(*) from public.matches where scheduled_at::date = current_date and status = 'completed')::integer,
        (select count(*) from public.matches where scheduled_at::date = current_date and status = 'upcoming')::integer,
        ns.sync_type,
        ns.scheduled_at
    from (select 1) as dummy
    left join public.api_usage au on au.usage_date = current_date
    cross join public.get_today_game_window() as gw
    left join lateral public.get_next_sync() as ns on true;
$$;


-- ============================================================
-- VERIFICAÇÃO
-- Confirmar que tudo foi criado corretamente
-- ============================================================

select 'api_config' as table_name, count(*) as rows from public.api_config
union all
select 'sync_schedule', count(*) from public.sync_schedule
union all
select 'api_requests', count(*) from public.api_requests
union all
select 'matches', count(*) from public.matches
union all
select 'players', count(*) from public.players
union all
select 'tournaments', count(*) from public.tournaments;
